cart/urls.py
from django.conf.urls import url
from cart import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "cart"
urlpatterns = [        
    url(r'^cart_add/(\d+)/$',views.cart_add,name='cart_add'),
    url(r'^cart_remove/(\d+)/$',views.cart_remove,name='cart_remove'),       
    url(r'^cart_detail/$',views.cart_detail,name='cart_detail'),
    ]

mystore/urls.py
from django.contrib import admin
from django.urls import path
from mystore import views
from django.conf.urls import url


app_name = "mystore"

app_name = "mystore"
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^product_detail/(\d+)/$', views.product_detail, name='product_detail'),
]

orders/urls.py
from django.conf.urls import url
from orders import views

urlpatterns = [
    url(r'^create/', views.order_create, name = 'order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

mystore/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=264,unique=True)
    fee = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to = "images/")
    def __str__(self):
        return str(self.name)

orders/models.py
from django.db import models
from mystore.models import Product

# Create your models here.
class Order(models.Model):
    first_name = models.CharField(max_length =50)
    last_name = models.CharField(max_length =50)
    email = models.EmailField()
    address = models.CharField(max_length =250)
    postal_code = models.CharField(max_length =20)
    city = models.CharField(max_length =100)
    created = models.DateTimeField(auto_now = True)
    updateted=  models.DateTimeField(auto_now = True) 
    paid = models.BooleanField(default = False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return'Order{}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):

    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity =models.PositiveIntegerField(default = 1)

    def __str__(self):
        return'{}'.format(self.id)
    
    def get_cost(self):
        return self.price * self.quantity

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 10)]
class CardAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(label= 'Sốlượng', choices = PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required = False, widget = forms.HiddenInput)

orders/forms.py
from django import forms
from orders.models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address','postal_code','city']

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mystore.models import Product
from .cart import Cart
from .forms import CardAddProductForm

# Create your views here.
@require_POST
def cart_add(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    form = CardAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product   =   product,   quantity   =   cd['quantity'],   update_quantity   = cd['update'])
        print(cart)    
        return redirect('cart:cart_detail')

def cart_remove(request, product_id=None):
    cart = Cart(request)
    product = get_object_or_404(Product, id = product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CardAddProductForm(initial     = {'quantity': item['quantity'], 'update': True} )
    return render(request, 'cart/cart_detail.html', {'cart':cart})

mystore/views.py
from django.shortcuts import render
from mystore.models import Product
from cart import forms
# Create your views here.
def index(request):
    pro_list = Product.objects.order_by('name')
    pro_dict = {"products":pro_list }
    return render(request, "mystore/index.html", context=pro_dict)

def product_detail(request, id=None):
    product = Product.objects.get(pk=id)
    cart_product_form = forms.CardAddProductForm()
    return render(request, 'mystore/product_detail.html', context= {'product': product })

orders/views.py
from django.shortcuts import render
from orders.models import OrderItem
from orders.forms import OrderCreateForm
from cart.cart import Cart
# Create your views here.
def order_create(request):
    cart = Cart(request)
    form = OrderCreateForm()
    if request.method == 'POST':
        print("I'm here")
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order = order,product = item['product'],price = item['fee'], quantity = item['quantity'])
                #clear the cart
                cart.clear()
                return render(request, 'orders/created.html', context = {'order' : order})
        else:
            form = OrderCreateForm()
    return render(request, 'orders/create.html',context={'form':form})

templates/cart/cart_detail.html
{% extends "mystore/base.html" %} 
{% block body_block %} 
	{% loadstaticfiles %}
	<div class="container">
	</div>
	<h1>Thông tin giỏ hàng</h1>
	<table class="table">
		<thead class="danger">
			<th>Sản phẩm</th>
			<th>Tên sản phẩm</th>
			<th>Số lượng</th>
			<th>Đơn giá (vnđ)</th>
			<th>Thành tiền (vnđ)</th>
			<th>Xóa</th>
		</thead>
		<tbody>
			{% for item in cart %}
			<tr class="success">
				<td>
					<ahref="{% url 'mystore:product_detail' item.product.pk%}">
						<imgsrc="{{item.product.image.url}}">
							</a>
				</td>
				<td>
					{{item.product.name}}
				</td>
				<td>
					<form action="{% url 'cart:cart_add' item.product.pk%}" method="post">
						{{item.update_quantity_form.quantity}} {{item.update_quantity_form.update}}
						<inputtype="submit" value="Cập nhật" /> {% csrf_token %}
					</form>
				</td>
				<td>{{item.fee}}</td>
				<td>{{item.total_fee}}</td>
				<td>
					<ahref="{% url 'cart:cart_remove' item.product.pk%}">Xóa</a>
				</td>
			</tr>
			{% endfor %}
			<tr class='total'>
				<td colspan="4"></td>
				<td class="num">Tổng: {{cart.get_total_fee}} vnđ</td>
			</tr>
		</tbody>
	</table>
	<p class="text-right">
		<a href="{% url 'mystore:index' %}" class="button light">Tiếp tục mua hàng</a>
		<a href="{% url 'orders:order_create'%}" class="btn btn-primary">Thanh toán</a>
	</p>
	</tbody>
	</table>
	</div>
	{% endblock %}
{% endblock %}

templates/mystore/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-tofit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Monkey Shop Online</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">MONKEY Shop Online</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" datatarget="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'mystore:index' %}">Home
<span class="sr-only">(current)</span>
</a>
                    </li>
                    <li class="nav-item">
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- Page Content -->
    <div class="container">
        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">ABC </h1>
            <p class="lead">All things you need are here! </p>
            <a href="#" class="btn btn-primary btn-lg">Contact!</a>
        </header>
    </div>
    <div class="container">
        {% block body_block %}
        <!-- Anything outsite of this will be inherited if you extend! -->
        {% endblock %}
        <div>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_detail'%}"> <img src="{%static 'images/card.png'%}" /></a>
            </li>
            <li class="cart">
                {% if cart %}
                <a class="nav-link" href="{% url 'cart:cart_detail'%}">Giỏ hàng có {{cart|length}} sản phẩm , VNĐ: {{cart.get_total_fee}}</a> {% else %}Giỏ hàng đang trống {% endif %}
            </li>
        </div>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'mystore:index' %}">Home
                <span class="sr-only">(current)</span> 
            </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{%   url   'cart:cart_detail'%}" style="background-image: url({%static " images/card.png " %})">Cart</a>
                </li>
            </ul>
        </div>
        <!-- Footer -->
        <footer class="py-5 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; by Monkey Website 2020</p>
            </div>
            <!-- /.container -->
        </footer>
        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js'%}"></script>
        <script src="{% static 'vendor/popper/popper.min.js'%}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js'%}">
        </script>
</body>

</html>

templates/mystore/index.html
<!DOCTYPE html>
{% extends "mystore/base.html" %}
{% block body_block %}
{% load static %}
<!-- Page Features -->
<div class="row text-center">
{% if products %}
{% for value in products %}
<div class="col-lg-3 col-md-6 mb-4">
<div class="card">
<img class="card-img-top" src="{{value.image.url}}" alt="{{value.name}}">
<div class="card-body">
<h4 class="card-title">{{value.name}}</h4>
<p class="card-text">{{value.description}}<br/>{{value.fee}} vnđ</p>
</div>
<div>
<a href="{% url 'mystore:product_detail' value.pk%}" class='btn btnprimary' style="float: center;" > Xem thêm </a>
</div>
</div>
</div>
{% endfor %}
{% endif%}
</div>
{% endblock %}

templates/mystore/product_detail.html
<!DOCTYPE html>
{% extends "mystore/base.html" %}
{% block body_block %}
{% load static %}
<!-- Page Features -->
<div class="row text-center">
{% if product %}
<div class="container">
<div class="card">
<img class="img-responsive" src="{{product.image.url}}"
alt="{{product.name}}" width="350" height="350"/>
<div class="card-body">
<h4 class="card-title">{{product.name}}</h4>
<p class="card-text">{{product.description}}<br/>{{product.fee}} vnđ</p>
</div>
<div>
    <formaction="{% url 'cart:cart_add' product.pk%}"method="post">
        {{cart_product_form}}
        {% csrf_token %}
        <div class="card-footer">
            <inputtype="submit"value="Thêm vào giỏ hàng"class="btn btn-primary">
        </div>
    </form>
</div>
</div>
</div>
{% endif%}
</div>
{% endblock %}

templates/orders/create.html
{% extends "mystore/base.html" %} {% block body_block %} {% load staticfiles %}
<div class="container"></div>
<table align="center">
    <tr>
        <td valign="top" width='50%'>
            <h1>Khách hàng</h1>
            <form action="." method="post">
                <table>
                    {% for field in form %}
                    <tr>
                        <td>{{field.label}} </td>
                        <td>{{field}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="2" align="center">
                            <p><input type="submit" value="Đặt hàng" class="btn btn-primary"></p>
                        </td>></tr>
                </table>
                {% csrf_token %}
            </form>
        </td>
        <td valign="top">
            <h1>Chi tiết đơn hàng</h1>
            <ul>
                {% for item in cart %}
                <li>
                    {{item.quantity}} tivi x {{item.product.name}} = <span>{{item.total_fee}}</span>
                </li>
                {% endfor %}
            </ul>
            <ul>Tổng: {{cart.get_total_fee}} vnđ</ul>
        </td>
    </tr>
</table>
</div>
{% endblock %} {% extends "mystore/base.html" %} {% block body_block %}
<div class="container">
    <h1>Đặt hàng thành công</h1>
    <p>Đơn đặt hàng của bạn đã đặt thành công. Mã đơn hàng <strong>{{order.id}}</strong></p>
</div>
{% endblock %}